baseURL: "https://www.liyangjie.cn:4443/"
title: 仙羡小站
paginate: 5
theme: PaperMod
defaultContentLanguage: cn

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    # 偷懒，直接使用en的国际化
    cn:
        languageName: "Chinese"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 15
                - name: Search
                  url: search/
                  weight: 16
                - name: Tags
                  url: tags/
                  weight: 14
                - name: Categories
                  url: categories/
                  weight: 13
    # en:
    #     languageName: "English"
    #     weight: 1
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives
    #               weight: 15
    #             - name: Search
    #               url: search/
    #               weight: 16
    #             - name: Tags
    #               url: tags/
    #               weight: 14
    #             - name: Categories
    #               url: categories/
    #               weight: 13
    

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "SadBird的狗窝-工作、学习和生活"
    author: SadBird
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    # ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["https://images.liyangjie.cn/image/SadBird.png"] # link or path of image for opengraph, twitter-cards

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    homeInfoParams:
        Title: "SadBird的狗窝"
        Content: >
            怨无大小，生于所爱；物无美恶，过则为灾。
    socialIcons:
        - name: email
          url: "mailto:foreverxianxian@gmail.com"
        - name: telegram
          url: "https://web.telegram.org/"
        - name: RsS
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    label:
        text: "仙羡小站"
        icon: "http://images.liyangjie.cn/image/earlybirds.png"
        iconHeight: 30

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "/favicon/favicon.ico"
        favicon16x16: "/favicon/favicon-16x16.png"
        favicon32x32: "/favicon/favicon-32x32.png"
        apple_touch_icon: "/favicon/apple-touch-icon.png"
        safari_pinned_tab: "/favicon/safari-pinned-tab.svg"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

#pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true